on:
  push:
  pull_request:

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.72.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Cache mdBook binaries
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/mdbook*
            ~/.cargo/.crates2.json
            ~/.cargo/.crates.toml
          key: ${{ runner.os }}-mdbook-${{ matrix.rust }}-${{ hashFiles('ci/install_mdbook.sh') }}

      - name: Install mdBook
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          ./ci/install_mdbook.sh

      - name: Build book
        run: |
          mdbook build
